spring.graphql.graphiql.enabled=false
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.mail.host=${SPRING_MAIL_HOST:localhost}
spring.mail.port=${SPRING_MAIL_PORT:1025}
spring.mail.username=
spring.mail.password=
spring.mail.properties.mail.smtp.auth=false
spring.mail.properties.mail.smtp.starttls.enable=false
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/weddingdb}
spring.datasource.username=${DB_USERNAME:weddingapp}
spring.datasource.password=${DB_PASSWORD:weddingapp123}
jwt.secret=${JWT_SECRET:s%[Lt%Nc9Qia1ulCL"£<539aW!41a8|3,|=h&K/]!2$3,5+*w8}
jwt.expiration-ms=${JWT_EXPIRATION:86400000}
app.base-url=${APP_BASE_URL:http://localhost:3000}
app.mail.from=${MAIL_FROM:invitations@weddingapp.com}